# Generated by Django 2.2.2 on 2019-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
