# Generated by Django 2.2.2 on 2019-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20190708_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
